### ISSUE TITLE
lrm regression test failed

### ISSUE THREAD

**Issue by lcq170** [ClusterLabs/cluster-glue#17]
### Reproduce Step
cd /usr/share/cluster-glue/lrmtest 
HA_BIN=/usr/lib64/heartbeat/ ./regression.sh

### Result
starting lrmd 
rscmgmt...................... checking... FAIL 
metadata........... checking... FAIL 
rscexec............................ checking... FAIL 
stonith checking... FAIL 
serialize checking... FAIL 
flood checking... FAIL 
seems like some tests failed or else something not expected 
check output/regression.out and diff files in output 
in case you wonder what lrmd was doing, read output/lrmd.log and output/lrmd.debug 
stopping lrmd 

### Analyze
1.  checked regression.out,  there are so many warning like "WARN: Can't connect to lrmd!" 
2.  checked lrmd.debug,  seems lrmd not work well  since ERROR: unregister_client: can not find client, but the client seems have regisered "on_msg_register:client lrmadmin [2599] registered".  

@krig @dmuhamedagic @lge 
Could you please help to check this problem, log have attached. Thanks.
[output.tar.gz](https://github.com/ClusterLabs/cluster-glue/files/2118696/output.tar.gz)

**Comment by dmuhamedagic** [comment]
This should work, but I haven't looked at it for a very long
time.

Anyway, lrmd from cluster-glue is not used in the pacemaker stack
anymore. What is your use case?

**Comment by lcq170** [comment]
Thanks.  I will close this issue since the test case is old,  lrmd in cluster-glue not used now.
