### ISSUE TITLE
hacluster user has /bin/bash shell in SUSE

### ISSUE THREAD

**Issue by andrewlukoshko** [ClusterLabs/cluster-glue#25]
%pre script in cluster-glue-suse.spec creates hacluster user with default /bin/bash shell. Is it really needed?
Fedora's %pre script creates hacluster user with proper /sbin/nologin shell, just like in every Pacemaker/Corosync doc I've seen.

**Comment by dmuhamedagic** [comment]
The spec file is just a sample. Distributions decide on the actual installation.
