### ISSUE TITLE
What exactly does monitor (aka status) action do?

### ISSUE THREAD

**Issue by ak2766** [ClusterLabs/cluster-glue#37]
I'm setting a highly available persistence storage cluster using `DRBD + NFS` and need to setup `stonith`.  Searching led me here and I downloaded the ec2 plugin to one of the cluster instances.  I tested rebooting one of the other nodes using the command below and it works - takes about ~40 secs return but I can see that the instances actually reboots - awesome:

```sh
./ec2 -n instance_name -o reboot
```

However, the `status` action always returns code `0` even when given the name of a non-existent instance - why?

**Comment by dmuhamedagic** [comment]
On Fri, Apr 15, 2022 at 11:34:19PM -0700, Anthony Kamau wrote:
> I'm setting a highly available persistence storage cluster using `DRBD + NFS` and need to setup `stonith`.  Searching led me here and I downloaded the ec2 plugin to one of the cluster instances.  I tested rebooting one of the other nodes using the command below and it works - takes about ~40 secs return but I can see that the instances actually reboots - awesome:
> 
> ```sh
> ./ec2 -n instance_name -o reboot
> ```
> 
> However, the `status` action always returns code `0` even when given the name of a non-existent instance - why?

By definition, the exit status of a stonith plugin shows if the
plugin is functional and ready. It doesn't show the status of the
host that the plugin manages.

**Comment by ak2766** [comment]
@dmuhamedagic - thanks for the explanation.

I'll close this non-issue.
