### ISSUE TITLE
use of deprecated method

### ISSUE THREAD

**Issue by jamincollins** [ClusterLabs/cluster-glue#40]
```
cl_poll.c: In function 'cl_poll_prepsig':
cl_poll.c:184:9: error: 'siginterrupt' is deprecated: Use sigaction with SA_RESTART instead [-Werror=deprecated-declarations]
  184 |         if (CL_SIGINTERRUPT(nsig, FALSE) < 0) {
      |         ^~
In file included from /usr/include/sys/param.h:28,
                 from ../../include/lha_internal.h:43,
                 from cl_poll.c:1:
/usr/include/signal.h:324:12: note: declared here
  324 | extern int siginterrupt (int __sig, int __interrupt) __THROW
      |            ^~~~~~~~~~~~
cc1: all warnings being treated as errors
```

**Comment by dmuhamedagic** [comment]
This is not the only deprecated warning, so I'm afraid that cluster-glue cannot be built with  -Werror=deprecated-declarations. It would simply be too much effort to get rid of all deprecated stuff. Which platform are you trying to build this on? I just checked Debian and it doesn't treat deprecated stuff as errors.

**Comment by jamincollins** [comment]
Arch Linux:

```
./autogen.sh
./configure
make
```

Results in `cc1: all warnings being treated as errors`.

Removing the `-Werror` from this line:
https://github.com/ClusterLabs/cluster-glue/blob/master/configure.ac#L1297

Allows the build to complete.  Alternatively, the default for `--enable-fatal-warnings` could be set to no and probably should be given that you know you're using deprecated features that will trip it up.

**Comment by dmuhamedagic** [comment]
Fixed.
