### ISSUE TITLE
Conflicting declarations of variable ipc_pollfunc_ptr

### ISSUE THREAD

**Issue by wferi** [ClusterLabs/cluster-glue#7]
*Quoting a Debian [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=688514):*

While building the package using our research compiler infrastructure we
noticed the following conflicting declarations:

- `./lib/clplumbing/ipcsocket.c:extern int (*ipc_pollfunc_ptr)(struct pollfd *, nfds_t, int);`
- `./lib/clplumbing/ocf_ipc.c:int (*ipc_pollfunc_ptr)(struct pollfd*, unsigned int, int)`

with `nfds_t` being `unsigned long int`. This may cause undefined behaviour if
values larger than `UINT_MAX` are passed to `*ipc_pollfunc_ptr`.

**Comment by dmuhamedagic** [comment]
On Tue, Dec 20, 2016 at 12:37:16AM -0800, wferi wrote:
> with `nfds_t` being `unsigned long int`.

It is unsigned int:

include/lha_internal.h:125     typedef unsigned int nfds_t;

Looking through the history couldn't find that it ever was long.

**Comment by wferi** [comment]
Ah, I didn't check. Good to know that it isn't causing problems now. Why don't you use the same type name to exclude any possibility of conflict?

**Comment by dmuhamedagic** [comment]
On Tue, Dec 20, 2016 at 03:49:27PM -0800, wferi wrote:
> Ah, I didn't check. Good to know that it isn't causing problems now. Why don't you use the same type name to exclude any possibility of conflict?

No idea, haven't been around when this type got introduced. But,
as mentioned in the previous comment, it has never been "long
unsigned", so I'm not sure how it could have ever caused an issue.

**Comment by wferi** [comment]
The problem is the typedef provided by the system `poll.h`. Here `/usr/include/sys/poll.h` (which is the actual header file reached via `poll.h`) contains:

    typedef unsigned long int nfds_t;

and it wins, because the typedef in `lha_internal.h` is conditional.

**Comment by dmuhamedagic** [comment]
Yes, you're right. Fixed now. Thanks for reporting and persisting!
